#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  creationTimestamp: "2022-06-17T15:33:43Z"
  generation: 1
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: hungryman
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/workload-type: server
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: hungryman-crawler
    carto.run/workload-namespace: #@ data.values.workloadNamespace
    networking.knative.dev/visibility: cluster-local
  name: hungryman-crawler
  namespace: #@ data.values.workloadNamespace
spec:
  params:
  - name: gitops_ssh_secret
    value: #@ data.values.gitOpsSecret
  - name: gitops_sub_path
    value: config/workloads/hungryman-crawler
  source:
    git:
      ref:
        branch: main
      url: #@ data.values.gitOpsRepo