#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: hungryman-api-gateway
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-api-gateway
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-search
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: hungryman-search
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-hungryman
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-search
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-search-proc
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: hungryman-search-proc
    networking.knative.dev/visibility: cluster-local
spec:
  env: 
  - name: spring_profiles_active
    value: crawler
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-hungryman
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-search-proc
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-notify
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: hungryman-notify
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-hungryman
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-notify
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-availability
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: hungryman-availability
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-hungryman
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-availability
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-ui
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: hungryman-ui
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 3000
      name: http
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-ui
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-crawler
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: hungryman-crawler
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8080
      name: http
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-crawler
